#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# pythonPremierProgrammeBonnePratique.py
#
# Copyright 2014 yves Mercadier <yves.mercadier@ac-montpellier.fr>
#
print (" ---> Debut du programme.")
#Les entrees du programme
prenom = input("Quel est ton prenom?")
annee = int(input("Quelle est ton ,annee, de naissance? "))
#le calcul
age = 2015-annee
#les sorties du programme
print ("Bonjour "+prenom+" .")
print ("En 2015 tu auras " ,age, "ans.")
print ("---> Fin du programme.")
